### ISSUE TITLE
How do I convert layers into PSD file using pytoshop?

### ISSUE THREAD

**Issue by geminthair** [mdboom/pytoshop#13]
* psdwriter version: 0.5.0
* Python version: 3.7
* Operating System: IOS 

### Description

I‘m trying to parse a PSD file into separated layers, and write the after parsed layers into a new PSD file.
The error occurred in "new_psd = pytoshop.user.nested_layers.nested_layers_to_psd([new_layer3[0]], color_mode=3, version=1, compression=1, depth=8, vector_mask=False)",
error message: "TypeError: decode() takes 1 positional argument but 5 were given".
Thank you github community.

### What I Did

```
Paste the command(s) you ran and the output.

import pytoshop
from pytoshop.user import nested_layers
from pytoshop import enums
from scipy import misc #read png
from PIL import Image
import numpy as np

with open('test.psd', 'rb') as fd:
psd = pytoshop.read(fd)
print(psd)
new_layer3 =pytoshop.user.nested_layers.psd_to_nested_layers (psd)
print(new_layer3[0])
new_psd = pytoshop.user.nested_layers.nested_layers_to_psd([new_layer3[0]], color_mode=3, version=1, compression=1, depth=8, vector_mask=False)
with open('newfile.psd', 'wb') as fd:
new_psd.write(fd) #

Error message:
<pytoshop.core.PsdFile object at 0x10da95da0>
<pytoshop.user.nested_layers.Image object at 0x116d9f5f8>
Traceback (most recent call last):
File "test3.py", line 13, in 
new_psd = pytoshop.user.nested_layers.nested_layers_to_psd([new_layer3[0]], color_mode=3, version=1, compression=1, depth=8, vector_mask=False)
File "/Users/kaven1912/Desktop/python_folder/envname/lib/python3.7/site-packages/pytoshop/user/nested_layers.py", line 841, in nested_layers_to_psd
layers, [], [], compression, vector_mask)
File "/Users/kaven1912/Desktop/python_folder/envname/lib/python3.7/site-packages/pytoshop/user/nested_layers.py", line 670, in _flatten_layers
layer, flat_layers, group_ids, compression, vector_mask
File "/Users/kaven1912/Desktop/python_folder/envname/lib/python3.7/site-packages/pytoshop/user/nested_layers.py", line 605, in _flatten_image
np.all(channels[enums.ChannelId.transparency].image == 0)):
File "/Users/kaven1912/Desktop/python_folder/envname/lib/python3.7/site-packages/pytoshop/layers.py", line 551, in image
self._shape, self._depth, self._version)
File "/Users/kaven1912/Desktop/python_folder/envname/lib/python3.7/site-packages/pytoshop/codecs.py", line 265, in decompress_image
return decompressors[compression](data, shape, depth, version)
File "/Users/kaven1912/Desktop/python_folder/envname/lib/python3.7/site-packages/pytoshop/codecs.py", line 158, in decompress_rle
data, shape[0], shape[1], color_depth_size_map[depth], version)
TypeError: decode() takes 1 positional argument but 5 were given


If there was a crash, please include the traceback here.
```

**Comment by mdboom** [comment]
Can you provide your psd file so I can try to reproduce the issue?

**Comment by solitarysandman** [comment]
Any updates on this?

**Comment by mdboom** [comment]
I can't reproduce without the input file.  @solitarysandman : If you're also seeing the same issue, maybe you could provide your test case?
